### ISSUE TITLE
sometimes agents load with black color

### ISSUE THREAD

**Issue by toloudis** [simularium/simularium-viewer#140]
## Description

Sometimes agents load with black color

## Expected Behavior

No agents should be black

## Reproduction

load each known trajectory in viewer and see if any agents are black.  **Mostly we need to see if this bug is still happening and if so, evaluate whether it's bad code or bad data.**

## Environment

Seems to be all browsers?

**Comment by blairlyons** [comment]
I haven't seen this in a long time, we can file a new bug if we see it again
