### ISSUE TITLE
Zero radius after switching Drag-and-Drop <-> Network file

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-viewer#156]
## Description

_A clear description of the bug_

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by toloudis** [comment]
Can this be reproduced?  Need example repro steps and a description of what actually goes wrong.

**Comment by blairlyons** [comment]
this was brought over from JIRA last year and I'm not sure who opened it. I think we can probably close and create a new issue if we see it again.
