### ISSUE TITLE
Membrane mesh is not displaying in Endocytosis

### ISSUE THREAD

**Issue by EricJIsaac** [simularium/simularium-viewer#203]
## Description
The membrane mesh is missing in endocytosis playback on both staging & production

## Expected Behavior

The membrane mesh should be present

## Reproduction
go to:
https://staging.simularium.allencell.org/viewer?trajFileName=endocytosis.simularium

## Environment

Noticed after update the trajectoryinfo block in the data file to version 3

**Comment by toloudis** [comment]
Done!
