### ISSUE TITLE
Clean up `dragAndDropFileInfo` and `visData`

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-viewer#224]
I just did a search and I could only find getters and setters [for `dragAndDropFileInfo`], but nothing that actually called those getter and setters, but maybe I missed something. 

Just wanted to flag incase it's some code we can delete

**Comment by meganrm** [comment]
I think `cacheJSON` is also no longer used. visData could probably use a cleanup now that we have the LocalFileSimulator that I think is now taking care of these functions

**Comment by toloudis** [comment]
Definitely not used inside of viewer.   Did you check simularium-website for calls to cacheJSON and dragAndDropFileInfo?  If none then we can definitely delete it.
