### ISSUE TITLE
Prototype initial autoconversion UI - Smoldyn

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-viewer#237]
## Use Case
As a developer using the example viewer, I need to be able to provide additional display information about a trajectory through a UI before autoconverting it.

## Acceptance Criteria
- When a Smoldyn trajectory is loaded locally in the viewer, a UI menu opens to collect display data from the user according to the corresponding template
- When the user clicks a submit button, example data loads in the viewer
- Using the data the user provided is out of scope, for next issue https://github.com/simularium/simularium-lambdas/issues/1

## Details
This depends on UI templates being defined in https://github.com/simularium/simulariumio/issues/74 

The scope of this issue is only a prototype for developers, another later issue will make this into a production UI.

This is only in the example viewer. 

Only render required fields for now

This is only the first template. We will use this ticket to make a decision (ticket no.) on whether we will proceed in this manner for other templates.

**Comment by blairlyons** [comment]
I started XML templates for Smoldyn, I'm not sure if this is the best way, so we should discuss:
https://github.com/simularium/simulariumio/tree/feature/ui-templates/ui-templates

@meganrm @schoinh

**Comment by blairlyons** [comment]
@meganrm UI templates for Smoldyn are ready for implementation: https://github.com/simularium/simulariumio/tree/feature/ui-templates/ui-templates

**Comment by toloudis** [comment]
A/C still say "When the user clicks a submit button, the file is autoconverted and loads in the viewer" - is that still true for this ticket?
