### ISSUE TITLE
Release viewer with AO updates

### ISSUE THREAD

**Issue by jsavieo** [simularium/simularium-viewer#270]
## Use Case

_Please provide a use case to help us understand your request in context_

## Acceptance Criteria

_Please describe how you know this is done_

## Details

Needed for work to be finished on https://github.com/simularium/simularium-website/issues/326

**Comment by toloudis** [comment]
V3.3.3 is released with the AO changes

**Comment by blairlyons** [comment]
this release should include updating the version installed in website, but I just did it
