### ISSUE TITLE
ambient occlusion changes with zoom

### ISSUE THREAD

**Issue by toloudis** [simularium/simularium-viewer#303]
## Description

When zooming in or out, agents get dimmer or brighter and it is not clear why.
We suspect the screen space AO sampling.

## Expected Behavior

Basically want things to stay the same brightness against zooming.

If AO is the problem, consider scaling the spacing of AO samples with depth value.

**Comment by rheiland** [comment]
Agreed. Here's an example of what I'm seeing.

<img width="608" alt="Screen Shot 2023-04-21 at 5 45 21 AM" src="https://user-images.githubusercontent.com/1774917/233605426-7a1236bd-7a3c-4590-b7d3-9cb617d70c7f.png">
<img width="454" alt="Screen Shot 2023-04-21 at 5 44 47 AM" src="https://user-images.githubusercontent.com/1774917/233605433-68b94b11-2c43-49c1-b357-3b1aaa1e7dc3.png">

**Comment by blairlyons** [comment]
@toloudis Randy's test trajectory is [here](https://simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/physicell_ambient_occlusion_test.simularium)

**Comment by blairlyons** [comment]
and [another test file](https://simularium.allencell.org/viewer?trajUrl=https://aics-simularium-data.s3.us-east-2.amazonaws.com/trajectory/point_cloud_test.simularium) from Ritvik, this one is dim unless you zoom out
