### ISSUE TITLE
AO on mesh in plasma model

### ISSUE THREAD

**Issue by toloudis** [simularium/simularium-viewer#306]
## Description

One of the mesh objects in the plasma model looks like it is receiving bad lighting.  

## Expected Behavior

It should look like the rest of the scene geometry.  We need to investigate and just make sure that nothing is wrong with the mesh or with our ao and lighting calculations for it. (Test it in isolation with other geometry turned off, etc)

Graham and I could not remember how we confirmed that things were correct, and he said it still looks funky.

**Comment by blairlyons** [comment]
This model lgtm in the staging viewer, so I'm going to close this and we can add a new issue if it comes up again
