### ISSUE TITLE
Initial camera view zoomed far out

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-viewer#330]
## Description
The camera starts further zoomed out since recent camera mode changes.

## Expected Behavior
The initial camera view should be similar even with the camera mode updates.

## Reproduction
1. Load [this trajectory](https://simularium.allencell.org/viewer?trajUrl=https://www.dropbox.com/scl/fi/2srfuliyjnu3sr1tlfgwf/cells_2023-10-04.simularium?rlkey=hg35vs9cwrla19eq2m0al81t4) from a collaborator.
2. Load [the same file](https://staging.simularium.allencell.org/viewer?trajUrl=https://www.dropbox.com/scl/fi/2srfuliyjnu3sr1tlfgwf/cells_2023-10-04.simularium?rlkey=hg35vs9cwrla19eq2m0al81t4) on staging (which has the camera mode updates v3.6.2) 

## Environment
Firefox, staging

**Comment by ShrimpCryptid** [comment]
Had a discussion with Blair about this! 

I implemented a fix that applies some smart scaling, but Dan pointed out that it doesn't respect the provided camera data in Simularium files. On looking closer, it seems like the camera data for the example file *is* provided (using a default setting, Z=120), so doing a check for missing camera data would not solve this case.

Blair says she doesn't want to do any "smart fixes" and it may be best to just leave the viewer as-is; the files will need to be updated on the scientist's end.

@toloudis feel free to close this if that seems sensible to you!

**Comment by ShrimpCryptid** [comment]
- [ ] Check if this is a fix we should add in Simularium I/O

**Comment by ShrimpCryptid** [comment]
Closed, idea continued in https://github.com/simularium/simularium-planning/issues/191.
