### ISSUE TITLE
Fiber subpoint positions should be relative to agent position

### ISSUE THREAD

**Issue by ascibisz** [simularium/simularium-viewer#332]
## What needs to happen?
Currently, the position of fiber points are represented as subpoints in simularium file format and are not relative to the agent position. By comparison, for sphere groups (which is the only simularium agent type that uses subpoints right currently), the subpoint position are interpreted as a delta relative to the agent position. It would be nice if fiber subpoints behaved the same way as that.

In simulariumio, we do keep the agent position at (0,0,0) for fibers, so technically fiber subpoint positions for simularium trajectories are relative to the agent position since it's the origin, so backwards compatibility shouldn't be an issue.

Once this task is done, simulariumio's translate functions can be updated to just translate the agent position, and leave the subpoints be.

## Why should we do this?
It'd be nice if the way we handled subpoints was consistent across different agent types.  Plus, I'm not really sure how rotation information is being interpreted for the subpoint data and if we should actually be translating the agent position in order for rotation to work properly? I played around a little bit with manipulating rotation data for fiber agents and I didn't notice any weirdness, but it would be great if someone could confirm that rotations are happening as expected with translated and rotated fiber data.

This was discussed as in [this comment thread](https://github.com/simularium/simulariumio/pull/152#discussion_r1268371212) on a simulariumio PR.

**Comment by toloudis** [comment]
I think agent translation and rotation should affect the positions of the subpoints in the same way they affect vertices of a mesh:  for all  subpoints, we would apply the rotation first (about the object's origin aka 0,0,0) and then translate to the agent position.

This would cause problems for any trajectories that expect the subpoints to be in world space and not local space, if there is a nonzero rotation applied.   I'm not sure such a thing exists currently, but it does mean we have to pay attention when using rotation angles for fiber agents.
An alternative system is adding some sort of data flag that says whether the subpoints are in local or world coordinates.

**Comment by blairlyons** [comment]
I think they should be local and we can add that to the documentation. Currently simulariumio uses zero positions and rotations for fibers, so the subpoints are local, although trivially. I think it makes sense to fix the viewer first and then we can make sure simulariumio does this properly in https://github.com/simularium/simulariumio/issues/109

**Comment by toloudis** [comment]
closed by #333
