### ISSUE TITLE
clear out cache of local simulation after a certain size 

### ISSUE THREAD

**Issue by meganrm** [simularium/simularium-viewer#372]
## Use Case

when running a simulation on the front end, you can just keep adding frames infinitely 

## Acceptance Criteria

The cache should have an upper size limit, 
possibly a setting that lets you define how much you want to keep (number of frames? or a size?)

## Details

_Please provide any helpful specifications_

**Comment by blairlyons** [comment]
This will also be helpful for visualizing large NERDSS trajectories

**Comment by meganrm** [comment]
how large to the NERDSS trajectories get @blairlyons
